using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum StoryEvent {

    ACCUEIL,
    USE_COMPUTER,
    TAKE_NOTEPAD,
    TAKE_PENCIL,
    TAKE_MARIA_LETTER,
    TAKE_EMPLOYMENT_CONTRACT,
    TAKE_GOOD_PRACTICE_GUIDE,
    USE_CHOCOLATE,
    USE_COFFEECUP,
    READ_MATERIAL_LIST,
    USE_TED_COMPUTER,
    READ_FOLLOW_ARRAY,
    USE_CHARLE_COMPUTER,
    USE_YANN_COMPUTER,
    LOOK_CHARLES_FAMILY_PICTURE,
    LOOK_YANN_CHILDREN_DRAW,
    SPEAK_TO_YANN,
    SPEAK_TO_YANN_ACCOUNT_PROBLEM,
    SPEAK_TO_YANN_PRESENTATION,
    SPEAK_TO_TED_PRESENTATION,
    SPEAK_TO_TED_ACCOUNT_PROBLEM,
    SPEAK_TO_CHARLES_PRESENTATION,
    SPEAK_TO_CHARLES_ACCOUNT_PROBLEM,
    FIND_COMPUTER_ID,
    INVENTORY_CLICK_MARIAS_LETTER,
    INVENTORY_CLICK_NOTEBOOK,
    INVENTORY_CLICK_PENCIL,
    INVENTORY_CLICK_CONTRACT,
    INVENTORY_CLICK_GOOD_PRACTICE_GUIDE,

}

